# Compose file generated automatically

version: '3.6'

services:
  simplerisk:
    environment:
    - DB_SETUP=automatic
    - DB_SETUP_PASS=8Ex4zOj5Y44g-axlXoF_s
    - SIMPLERISK_DB_HOSTNAME=mysql
    image: simplerisk/simplerisk-minimal:20240930-001
    ports:
    - "80:80"
    - "443:443"

  mariadb:
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
    environment:
    - MYSQL_ROOT_PASSWORD=8Ex4zOj5Y44g-axlXoF_s
    image: mysql:8.0

  smtp:
    image: namshi/smtp
